spring:
  profiles: test
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url:  jdbc:h2:mem:appointmentsDb
    driver-class-name:  org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
      database-platform:  org.hibernate.dialect.MySQL55Dialect
      generate-ddl: true
      show-sql: true
server:
  port: 8081